=== Garibel-Lee/WB_sec_homework/src/day11/Config.dtd
<?xml version="1.0" encoding="UTF-8"?>
        <!ELEMENT beans (bean+)>
        <!ELEMENT bean (property+)>
        <!ELEMENT property (#PCDATA)>

        <!ATTLIST bean id ID #IMPLIED>
        <!ATTLIST bean class CDATA #IMPLIED>
        <!ATTLIST bean name CDATA #IMPLIED>
        <!ATTLIST property name CDATA #IMPLIED>
        <!ATTLIST property value CDATA #IMPLIED>

=== Garibel-Lee/WB_sec_homework/src/day11/app.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE beans SYSTEM "src/day11/Config.dtd">
<beans>

    <bean id = "dataSource" class="com.mchange.v2.c3p0.ComboPooledDataSource">
        <property name="driverClass" value="${db.driver}"/>
        <property name="jdbcUrl" value="${db.url}"/>
        <property name="user" value="${db.username}"/>
        <property name="password" value="${db.password}"/>
    </bean>

    <bean id = "sqlSessionFactory" name="sqlSessionFactory" class="org.mybatis.spring.SqlSessionFactoryBean">
        <property name="configLocation" value="classpath:mybatit-config.xml"/>
        <property name="dataSource"/>
        <property name="typeAliasesPackage" value="day20.entity"/>
        <property name="mapperLocations" value="classpath:com/wbhz/mapper/*.xml"></property>
    </bean>

    <bean  class="org.mybatis.spring.mapper.MapperScannerConfigurer">
        <property name="basePackage" value="day20.mapper"/>
        <property name="sqlSessionFactoryBeanName" value="sqlSessionFactory"/>
    </bean>



</beans>
